-- Recreate access_codes with dollar amounts
CREATE TABLE public.access_codes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code text NOT NULL UNIQUE,
  coach_name text NOT NULL,
  role text NOT NULL CHECK (role IN ('admin', 'coach')),
  commission_per_workout int NOT NULL DEFAULT 10
);

INSERT INTO public.access_codes (code, coach_name, role, commission_per_workout) VALUES
  ('ADMIN-99', 'Admin User', 'admin', 0),
  ('COACH-123', 'Coach One', 'coach', 2),
  ('COACH-456', 'Coach Two', 'coach', 2);

create table if not exists public.workout_logs (
  id bigint generated by default as identity primary key,
  coach_code text not null,
  client_name text not null,
  client_gender text not null,
  client_age int not null,
  client_height_cm int not null,
  client_weight_kg int not null,
  course_name text,
  exercises_json jsonb not null,
  created_at timestamptz not null default now()
);

create index if not exists workout_logs_coach_code_idx on public.workout_logs (coach_code);
create index if not exists workout_logs_created_at_idx on public.workout_logs (created_at desc);

alter table public.workout_logs add column course_name text;
alter table public.workout_logs enable row level security;

revoke all on table public.access_codes from anon;
revoke all on table public.workout_logs from anon;
revoke all on table public.access_codes from authenticated;
revoke all on table public.workout_logs from authenticated;
